[project]
name = "notion-brain-dump"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.49.0",
    "mcp[cli]>=1.6.0",
    "notion-client>=2.3.0",
    "python-dotenv>=1.1.0",
]
